version: '3.8'

services:
  backend:
    build:
      context: ./ai-ticket-assistant
      dockerfile: Dockerfile
    container_name: ai-ticket-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # AWS region for Secrets Manager (IAM role will provide credentials)
      - AWS_REGION=${AWS_REGION:-us-east-1}
      # App configuration
      - APP_URL=${APP_URL:-http://localhost:3000}
    networks:
      - ai-ticket-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./ticket-system-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: ai-ticket-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - ai-ticket-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes: {}

networks:
  ai-ticket-network:
    driver: bridge